# Generated by Django 4.0.3 on 2022-03-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlashSaleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email Address')),
                ('display_name', models.CharField(max_length=255, null=True, verbose_name='Display Name')),
                ('picture', models.URLField(max_length=512, null=True, verbose_name='Picture URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='User Active?')),
                ('type', models.CharField(choices=[('USER', 'USER'), ('OWNER', 'OWNER'), ('SUPERUSER', 'SUPERUSER')], default='USER', max_length=20, verbose_name='User Type')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
