"""
Django settings for lbsfaou project.

Generated by 'django-admin startproject' using Django 4.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from distutils.util import strtobool
from datetime import timedelta

from pathlib import Path

from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")
assert SECRET_KEY is not None, 'SECRET_KEY None'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(strtobool(os.environ.get("DEBUG", "1")))

# skip user verification , phone verification, business registration and so on..
# Don't use this feature on PRODUCTION
# Use only for TEST purpose
TEST_MODE_ON = bool(strtobool(os.environ.get("TEST_MODE_ON", "0")))

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # add accounts & flashsale
    'flashsale.apps.FlashsaleConfig',
    'accounts.apps.AccountsConfig',
    'rest_framework',
    'rest_framework_simplejwt',
    'social_django',
    'mptt'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # add LocaleMiddleware for multilingual
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lbsfaou.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lbsfaou.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

# Added for multilingual support
# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'ko-KR'

LANGUAGES = [
    ('ko', _('Korean')),
    ('en', _('English')),
]

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'assets', 'locale'),
)


# TIME_ZONE = 'UTC'
# django timezone setting. change TIME_ZONE to Asia/Seoul
TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

# django timezone setting. change USE_TZ to False
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# FlashSale - add FlashSale User model
# django auth customization using AbstractBaseUser.
# please refer to https://docs.djangoproject.com/en/dev/topics/auth/customizing/#a-full-example
AUTH_USER_MODEL = 'accounts.FlashSaleUser'

# add REST_FRAMEWORK for FlashSale
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # GenericAPIView is used for rest framework, and authentication classes are re-defined in GenericAPIView
    # so different authentication is used for django session and rest framework session
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'EXCEPTION_HANDLER': 'flashsale.misc.lib.extends.custom_exception_handler',
}

# JWT settings
SIMPLE_JWT_ACCESS_TOKEN_LIFETIME_IN_DAY = int(os.environ.get('SIMPLE_JWT_ACCESS_TOKEN_LIFETIME_IN_DAY', 1))
SIMPLE_JWT_REFRESH_TOKEN_LIFETIME_IN_DAY = int(os.environ.get('SIMPLE_JWT_REFRESH_TOKEN_LIFETIME_IN_DAY', 15))
SIMPLE_JWT_SIGNING_KEY = os.environ.get('SIMPLE_JWT_SIGNING_KEY', SECRET_KEY)
SIMPLE_JWT_ALGORITHM = os.environ.get('SIMPLE_JWT_ALGORITHM', 'HS256')

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=SIMPLE_JWT_ACCESS_TOKEN_LIFETIME_IN_DAY),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=SIMPLE_JWT_REFRESH_TOKEN_LIFETIME_IN_DAY),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,

    'ALGORITHM': SIMPLE_JWT_ALGORITHM,
    'SIGNING_KEY': SIMPLE_JWT_SIGNING_KEY,
    'AUTH_HEADER_TYPES': ('JWT',),
}

AUTHENTICATION_BACKENDS = (
    'social_core.backends.facebook.FacebookOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

# Facebook Auth
SOCIAL_AUTH_FACEBOOK_KEY = os.environ.get("SOCIAL_AUTH_FACEBOOK_KEY")
assert SOCIAL_AUTH_FACEBOOK_KEY is not None, 'SOCIAL_AUTH_FACEBOOK_KEY None'
SOCIAL_AUTH_FACEBOOK_SECRET = os.environ.get("SOCIAL_AUTH_FACEBOOK_SECRET")
assert SOCIAL_AUTH_FACEBOOK_SECRET is not None, 'SOCIAL_AUTH_FACEBOOK_SECRET None'
SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {'fields': 'id, name, email, picture' }

# add Google client id here!!! for google authentication
FLASHSALE_GOOGLE_CLIENT_ID = os.environ.get('FLASHSALE_GOOGLE_CLIENT_ID')
assert FLASHSALE_GOOGLE_CLIENT_ID is not None, 'FLASHSALE_GOOGLE_CLIENT_ID None'

# FlashSale - setup django logging environment
# create log directory
LOGGING_ROOT = BASE_DIR / 'assets' / 'log'
LOGGING_ROOT.mkdir(parents=True, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'console': {
            'format': '%(name)-25s %(levelname)-8s %(message)s'
        },
        'file': {
            'format': '%(asctime)s %(name)-25s %(levelname)-8s %(funcName)-20s %(message)s'
        }
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'console'
        },
        'file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': os.path.join(LOGGING_ROOT, 'debug.log'),
            'when': "midnight",
            'formatter': 'file',
            'backupCount': 10,
            'interval': 1,
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'flashsale': {
            'level': 'DEBUG',
            'handlers': ['file', 'console'],
            'propagate': False,
        },
        'accounts': {
            'level': 'DEBUG',
            'handlers': ['file', 'console'],
            'propagate': False,
        },
    },
}
